image: python:alpine3.19

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

tree:
  script:
    - apk add git tree
    - cd "$CI_PROJECT_DIR/pygressus/"
    - tree

test:
  script:
    - python3 -m unittest discover -s test -p '*_test.py'
